// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStock.Classes.Models;

#nullable disable

namespace SmartStock.Migrations
{
    [DbContext(typeof(SmartStockContext))]
    [Migration("20260531171441_SeedCafeDataset")]
    partial class SeedCafeDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("SmartStock.Classes.Models.AiForecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PredictedDemand")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ForecastId");

                    b.HasIndex("ProductId");

                    b.ToTable("AiForecasts");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.AiStockRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecommendationId");

                    b.HasIndex("ProductId");

                    b.ToTable("AiStockRecommendations");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Hot Drinks",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cold Drinks",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Pastries",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            City = "Default City",
                            Email = "default@gmail.com",
                            FullName = "Default Customer",
                            IsActive = true,
                            Phone = "0000000000",
                            RegistrationDate = new DateTime(2026, 5, 31, 20, 14, 39, 183, DateTimeKind.Local).AddTicks(5609)
                        });
                });

            modelBuilder.Entity("SmartStock.Classes.Models.EconometricModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoefficientValue")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime>("LastTrainedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PValue")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RSquared")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ModelId");

                    b.HasIndex("ProductId");

                    b.ToTable("EconometricModels");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.ExternalFactor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpactValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FactorId");

                    b.ToTable("ExternalFactors");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CurrentStock = 800,
                            IsActive = true,
                            ProductName = "Americano",
                            SafetyStock = 150,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 14m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CurrentStock = 720,
                            IsActive = true,
                            ProductName = "Cappuccino",
                            SafetyStock = 150,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 16m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CurrentStock = 600,
                            IsActive = true,
                            ProductName = "Hot Tea",
                            SafetyStock = 120,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 12m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            CurrentStock = 300,
                            IsActive = true,
                            ProductName = "Hot Chocolate",
                            SafetyStock = 90,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 18m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            CurrentStock = 500,
                            IsActive = true,
                            ProductName = "Cold Brew",
                            SafetyStock = 120,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 20m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            CurrentStock = 480,
                            IsActive = true,
                            ProductName = "Iced Latte",
                            SafetyStock = 120,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 22m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            CurrentStock = 450,
                            IsActive = true,
                            ProductName = "Lemonade",
                            SafetyStock = 110,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 15m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            CurrentStock = 100,
                            IsActive = true,
                            ProductName = "Iced Tea",
                            SafetyStock = 110,
                            SupplierId = 1,
                            UnitOfMeasure = "cup",
                            UnitPrice = 14m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            CurrentStock = 400,
                            IsActive = true,
                            ProductName = "Croissant",
                            SafetyStock = 100,
                            SupplierId = 2,
                            UnitOfMeasure = "piece",
                            UnitPrice = 8m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            CurrentStock = 250,
                            IsActive = true,
                            ProductName = "Cheesecake",
                            SafetyStock = 80,
                            SupplierId = 2,
                            UnitOfMeasure = "slice",
                            UnitPrice = 12m
                        });
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.SaleDetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "123 Coffee St, Caffeine City",
                            ContactPerson = "John Doe",
                            Email = "coffee.john@gmail.com",
                            IsActive = true,
                            Phone = "1234567890",
                            SupplierName = "Coffee Supplier Inc."
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "45 Pastry Ave, Doughville",
                            ContactPerson = "Jane Roe",
                            Email = "bakery.jane@gmail.com",
                            IsActive = true,
                            Phone = "0987654321",
                            SupplierName = "Bakery Goods Ltd."
                        });
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsLoggedIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccessFailedCount = 0,
                            Email = "admin@gmail.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            IsLoggedIn = 0,
                            PasswordHash = "iGTO9GE1H7OewewKCbZankAG07wX7ij0stVqalFmbuE=",
                            Role = "Admin",
                            Salt = "StaticSaltForAdmin123!",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartStock.Classes.Models.AiForecast", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.AiStockRecommendation", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.EconometricModel", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Product", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStock.Classes.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Sale", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStock.Classes.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.SaleDetails", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStock.Classes.Models.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Transaction", b =>
                {
                    b.HasOne("SmartStock.Classes.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("SmartStock.Classes.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
